# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["backend_launcher.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("ems_system", "ems_system"),
        ("reports", "reports"),
        ("manage.py", "."),
    ],
    hiddenimports=[
        "django",
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "corsheaders",
        "rest_framework",
        "rest_framework_simplejwt",
        "reports",
        "reports.models",
        "reports.views",
        "reports.urls",
        "reports.serializers",
        "ems_system",
        "ems_system.settings",
        "ems_system.urls",
        "ems_system.wsgi",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="ems_backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)