// src/components/pages/Settings.jsx
import React, { useEffect, useState } from "react";
import Sidebar from "./Sidebar";
import "./Settings.css";

import { fetchWithAuth, clearAuth, getAccessToken } from "../../auth";

const API_BASE = "http://localhost:8000";

const DEFAULT_SETTINGS = {
  organizationName: "EMS CDRRMO",
  facilityName: "Patient Care Reporting System",
  address: "",
  contactNumber: "",
  email: "",
  reportFooterNote: "Generated by EMS Patient Care Reporting System • CDRRMO",
  autosaveEnabled: true,
};

function Settings() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [savedMsg, setSavedMsg] = useState("");
  const [error, setError] = useState("");
  const [settings, setSettings] = useState(DEFAULT_SETTINGS);

  const [acctLoading, setAcctLoading] = useState(true);
  const [acctSaving, setAcctSaving] = useState(false);
  const [acctMsg, setAcctMsg] = useState("");
  const [acctErr, setAcctErr] = useState("");
  const [account, setAccount] = useState({
    username: "",
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  });

  useEffect(() => {
    setLoading(true);

    const t = setTimeout(() => {
      const raw = localStorage.getItem("ems_settings");
      if (raw) {
        try {
          setSettings({ ...DEFAULT_SETTINGS, ...JSON.parse(raw) });
        } catch {
          // ignore corrupted data
        }
      }
      setLoading(false);
    }, 450);

    return () => clearTimeout(t);
  }, []);

  useEffect(() => {
    let mounted = true;

    async function loadMe() {
      setAcctLoading(true);
      setAcctErr("");

      try {
        const tok = getAccessToken();
        if (!tok) throw new Error("You are not logged in. Please login again.");

        const res = await fetchWithAuth(
          `${API_BASE}/api/auth/me/`,
          { method: "GET" },
          API_BASE
        );

        if (res.status === 401) {
          clearAuth?.();
          window.location.href = "/";
          return;
        }

        const data = await res.json().catch(() => ({}));
        if (!res.ok) {
          const msg = data?.detail || data?.error || "Failed to load user.";
          throw new Error(msg);
        }

        if (!mounted) return;
        setAccount((p) => ({ ...p, username: data?.username || "" }));
      } catch (e) {
        if (!mounted) return;
        setAcctErr(e?.message || "");
      } finally {
        if (!mounted) return;
        setAcctLoading(false);
      }
    }

    loadMe();

    return () => {
      mounted = false;
    };
  }, []);

  function updateField(key, value) {
    setSettings((prev) => ({ ...prev, [key]: value }));
  }

  function updateAccountField(key, value) {
    setAccount((prev) => ({ ...prev, [key]: value }));
  }

  async function saveAll(e) {
    e?.preventDefault?.();
    setSaving(true);
    setError("");
    setSavedMsg("");

    try {
      localStorage.setItem("ems_settings", JSON.stringify(settings));
      setSavedMsg("Settings saved.");
      setTimeout(() => setSavedMsg(""), 2000);
    } catch (err) {
      console.error(err);
      setError("Failed to save settings.");
    } finally {
      setSaving(false);
    }
  }

  function resetDefaults() {
    setSettings(DEFAULT_SETTINGS);
    localStorage.removeItem("ems_settings");
    setSavedMsg("Reset to defaults.");
    setTimeout(() => setSavedMsg(""), 2000);
  }

  async function saveAccount() {
    setAcctSaving(true);
    setAcctErr("");
    setAcctMsg("");

    const tok = getAccessToken();
    if (!tok) {
      setAcctErr("You are not logged in. Please login again.");
      setAcctSaving(false);
      return;
    }

    const wantsPasswordChange =
      account.currentPassword || account.newPassword || account.confirmPassword;

    if (wantsPasswordChange) {
      if (!account.currentPassword) {
        setAcctErr("Current password is required to change password.");
        setAcctSaving(false);
        return;
      }
      if (!account.newPassword) {
        setAcctErr("New password is required.");
        setAcctSaving(false);
        return;
      }
      if (account.newPassword.length < 8) {
        setAcctErr("New password must be at least 8 characters.");
        setAcctSaving(false);
        return;
      }
      if (account.newPassword !== account.confirmPassword) {
        setAcctErr("New password and confirm password do not match.");
        setAcctSaving(false);
        return;
      }
    }

    try {
      const payload = {
        username: account.username?.trim(),
        current_password: wantsPasswordChange ? account.currentPassword : undefined,
        new_password: wantsPasswordChange ? account.newPassword : undefined,
      };

      Object.keys(payload).forEach((k) => payload[k] === undefined && delete payload[k]);

      const res = await fetchWithAuth(
        `${API_BASE}/api/auth/account/`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        },
        API_BASE
      );

      if (res.status === 401) {
        clearAuth?.();
        window.location.href = "/";
        return;
      }

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        const msg =
          data?.detail ||
          data?.error ||
          (typeof data === "string" ? data : null) ||
          (data && typeof data === "object"
            ? Object.entries(data)
                .map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join(" ") : String(v)}`)
                .join(" • ")
            : null) ||
          "Failed to update account.";
        throw new Error(msg);
      }

      setAcctMsg("Account updated successfully.");
      setTimeout(() => setAcctMsg(""), 2200);

      setAccount((p) => ({
        ...p,
        currentPassword: "",
        newPassword: "",
        confirmPassword: "",
      }));
    } catch (e) {
      setAcctErr(e?.message || "Failed to update account.");
    } finally {
      setAcctSaving(false);
    }
  }

  const SkLine = ({ w = "100%", h = 12, r = 10, className = "" }) => (
    <div
      className={`st-skel ${className}`}
      style={{ width: w, height: h, borderRadius: r }}
      aria-hidden="true"
    />
  );

  const SkInput = () => (
    <div className="st-skel-input" aria-hidden="true">
      <SkLine w="28%" h={10} r={8} className="mb8" />
      <SkLine w="100%" h={40} r={12} />
    </div>
  );

  const SkTextarea = () => (
    <div className="st-skel-input" aria-hidden="true">
      <SkLine w="35%" h={10} r={8} className="mb8" />
      <SkLine w="100%" h={92} r={12} />
    </div>
  );

  return (
    <div className="st-layout">
      <Sidebar />

      <div className="st-main">
        <div className="st-page">
          <div className="st-head">
            <div>
              <div className="st-crumbs">Settings</div>

              {loading ? (
                <>
                  <SkLine w="180px" h={22} r={10} className="mb10" />
                  <SkLine w="320px" h={12} r={10} />
                </>
              ) : (
                <>
                  <h2 className="st-title">Settings</h2>
                  <p className="st-subtitle">
                    Customize organization details and report defaults.
                  </p>
                </>
              )}
            </div>

            <div className="st-actions">
              {loading ? (
                <>
                  <SkLine w="92px" h={40} r={12} />
                  <SkLine w="132px" h={40} r={12} />
                </>
              ) : (
                <>
                  <button className="st-btn st-btn-soft" onClick={resetDefaults} type="button">
                    Reset
                  </button>
                  <button
                    className="st-btn st-btn-primary"
                    onClick={saveAll}
                    disabled={saving}
                    type="button"
                  >
                    {saving ? "Saving..." : "Save Changes"}
                  </button>
                </>
              )}
            </div>
          </div>

          {!loading && (error || savedMsg) && (
            <div className={`st-alert ${error ? "danger" : "ok"}`}>
              <div className="st-alert-title">{error ? "Action failed" : "Success"}</div>
              <div className="st-alert-text">{error || savedMsg}</div>
            </div>
          )}

          <div className="st-grid">
            <section className="st-card">
              <div className="st-card-head">
                <div>
                  {loading ? (
                    <>
                      <SkLine w="220px" h={16} r={10} className="mb8" />
                      <SkLine w="260px" h={12} r={10} />
                    </>
                  ) : (
                    <>
                      <h3 className="st-card-title">Organization Profile</h3>
                      <p className="st-card-sub">Information shown on headers and reports</p>
                    </>
                  )}
                </div>
              </div>

              {loading ? (
                <div className="st-form">
                  <SkInput />
                  <SkInput />
                  <SkInput />
                  <div className="st-2col">
                    <SkInput />
                    <SkInput />
                  </div>

                  <div className="st-form-actions">
                    <SkLine w="110px" h={40} r={12} />
                  </div>
                </div>
              ) : (
                <form className="st-form" onSubmit={saveAll}>
                  <div className="st-row">
                    <label className="st-label">Organization Name</label>
                    <input
                      className="st-input"
                      value={settings.organizationName}
                      onChange={(e) => updateField("organizationName", e.target.value)}
                      placeholder="EMS CDRRMO"
                    />
                  </div>

                  <div className="st-row">
                    <label className="st-label">Facility / System Name</label>
                    <input
                      className="st-input"
                      value={settings.facilityName}
                      onChange={(e) => updateField("facilityName", e.target.value)}
                      placeholder="Patient Care Reporting System"
                    />
                  </div>

                  <div className="st-row">
                    <label className="st-label">Address</label>
                    <input
                      className="st-input"
                      value={settings.address}
                      onChange={(e) => updateField("address", e.target.value)}
                      placeholder="Office address"
                    />
                  </div>

                  <div className="st-2col">
                    <div className="st-row">
                      <label className="st-label">Contact Number</label>
                      <input
                        className="st-input"
                        value={settings.contactNumber}
                        onChange={(e) => updateField("contactNumber", e.target.value)}
                        placeholder="09xx..."
                      />
                    </div>

                    <div className="st-row">
                      <label className="st-label">Email</label>
                      <input
                        className="st-input"
                        value={settings.email}
                        onChange={(e) => updateField("email", e.target.value)}
                        placeholder="example@email.com"
                      />
                    </div>
                  </div>

                  <div className="st-form-actions">
                    <button className="st-btn st-btn-primary" type="submit" disabled={saving}>
                      {saving ? "Saving..." : "Save"}
                    </button>
                  </div>
                </form>
              )}
            </section>

            <section className="st-card">
              <div className="st-card-head">
                <div>
                  {loading ? (
                    <>
                      <SkLine w="200px" h={16} r={10} className="mb8" />
                      <SkLine w="240px" h={12} r={10} />
                    </>
                  ) : (
                    <>
                      <h3 className="st-card-title">Report Preferences</h3>
                      <p className="st-card-sub">Defaults applied to new reports</p>
                    </>
                  )}
                </div>
              </div>

              {loading ? (
                <div className="st-form">
                  <SkTextarea />

                  <div className="st-toggle-row">
                    <div style={{ width: "60%" }}>
                      <SkLine w="120px" h={12} r={10} className="mb8" />
                      <SkLine w="220px" h={10} r={10} />
                    </div>
                    <SkLine w="86px" h={36} r={999} />
                  </div>

                  <SkLine w="100%" h={44} r={12} />
                </div>
              ) : (
                <div className="st-form">
                  <div className="st-row">
                    <label className="st-label">Report Footer Note</label>
                    <textarea
                      className="st-textarea"
                      rows={3}
                      value={settings.reportFooterNote}
                      onChange={(e) => updateField("reportFooterNote", e.target.value)}
                      placeholder="Footer note shown on printed/exported reports..."
                    />
                  </div>

                  <div className="st-toggle-row">
                    <div>
                      <div className="st-toggle-title">Autosave</div>
                      <div className="st-toggle-sub">Save form progress automatically (local)</div>
                    </div>

                    <button
                      className={`st-toggle ${settings.autosaveEnabled ? "on" : ""}`}
                      type="button"
                      onClick={() => updateField("autosaveEnabled", !settings.autosaveEnabled)}
                    >
                      <span className="st-dot" />
                      <span className="st-toggle-text">
                        {settings.autosaveEnabled ? "On" : "Off"}
                      </span>
                    </button>
                  </div>

                  <div className="st-note">
                    Tip: Autosave uses your browser storage. Clearing browser data will remove
                    saved drafts.
                  </div>
                </div>
              )}
            </section>

            <section className="st-card st-card-wide">
              <div className="st-card-head">
                <div>
                  {acctLoading ? (
                    <>
                      <SkLine w="190px" h={16} r={10} className="mb8" />
                      <SkLine w="260px" h={12} r={10} />
                    </>
                  ) : (
                    <>
                      <h3 className="st-card-title">Account & Security</h3>
                      <p className="st-card-sub">Change username and password</p>
                    </>
                  )}
                </div>
              </div>

              {!acctLoading && (acctErr || acctMsg) && (
                <div className={`st-alert ${acctErr ? "danger" : "ok"}`}>
                  <div className="st-alert-title">{acctErr ? "Action failed" : "Success"}</div>
                  <div className="st-alert-text">{acctErr || acctMsg}</div>
                </div>
              )}

              {acctLoading ? (
                <div className="st-form">
                  <SkInput />
                  <div className="st-2col">
                    <SkInput />
                    <SkInput />
                  </div>
                  <SkInput />
                  <div className="st-form-actions">
                    <SkLine w="150px" h={40} r={12} />
                  </div>
                </div>
              ) : (
                <div className="st-form">
                  <div className="st-row">
                    <label className="st-label">Username</label>
                    <input
                      className="st-input"
                      value={account.username}
                      onChange={(e) => updateAccountField("username", e.target.value)}
                      placeholder="Enter new username"
                      autoComplete="username"
                    />
                  </div>

                  <div className="st-divider" />

                  <div className="st-2col">
                    <div className="st-row">
                      <label className="st-label">Current Password</label>
                      <input
                        className="st-input"
                        type="password"
                        value={account.currentPassword}
                        onChange={(e) => updateAccountField("currentPassword", e.target.value)}
                        placeholder="••••••••"
                        autoComplete="current-password"
                      />
                    </div>

                    <div className="st-row">
                      <label className="st-label">New Password</label>
                      <input
                        className="st-input"
                        type="password"
                        value={account.newPassword}
                        onChange={(e) => updateAccountField("newPassword", e.target.value)}
                        placeholder="At least 8 characters"
                        autoComplete="new-password"
                      />
                    </div>
                  </div>

                  <div className="st-row">
                    <label className="st-label">Confirm New Password</label>
                    <input
                      className="st-input"
                      type="password"
                      value={account.confirmPassword}
                      onChange={(e) => updateAccountField("confirmPassword", e.target.value)}
                      placeholder="Re-type new password"
                      autoComplete="new-password"
                    />
                  </div>

                  <div className="st-form-actions">
                    <button
                      className="st-btn st-btn-primary"
                      type="button"
                      onClick={saveAccount}
                      disabled={acctSaving}
                    >
                      {acctSaving ? "Updating..." : "Update Account"}
                    </button>
                  </div>

                  <div className="st-note">
                    Password changes require your current password. Leave password fields empty if
                    you only want to change username.
                  </div>
                </div>
              )}
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Settings;