# Generated by Django 6.0.2 on 2026-02-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('weight', models.CharField(blank=True, default='', max_length=30)),
                ('contact_number', models.CharField(blank=True, default='', max_length=40)),
                ('chief_complaint', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_body_no', models.CharField(max_length=60)),
                ('call_no', models.CharField(max_length=60)),
                ('case_no', models.CharField(max_length=60)),
                ('patient_location', models.TextField(blank=True, default='')),
                ('transported_to', models.TextField(blank=True, default='')),
                ('doi', models.DateField(blank=True, null=True)),
                ('toi', models.TimeField(blank=True, null=True)),
                ('poi', models.TextField(blank=True, default='')),
                ('moi', models.TextField(blank=True, default='')),
                ('call_received_time', models.DateTimeField(blank=True, null=True)),
                ('responded_time', models.DateTimeField(blank=True, null=True)),
                ('arrived_scene_time', models.DateTimeField(blank=True, null=True)),
                ('left_scene_time', models.DateTimeField(blank=True, null=True)),
                ('arrived_hospital_time', models.DateTimeField(blank=True, null=True)),
                ('back_in_service_time', models.DateTimeField(blank=True, null=True)),
                ('intervention_notes', models.TextField(blank=True, default='')),
                ('apgar_enabled', models.BooleanField(default=False)),
                ('non_transport_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingPhysicianNOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physician_nod', models.CharField(blank=True, default='', max_length=160)),
                ('signature_data_url', models.TextField(blank=True, default='')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_physician_nod', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='NonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_transport', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='GCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_score', models.CharField(blank=True, default='', max_length=40)),
                ('verbal_score', models.CharField(blank=True, default='', max_length=60)),
                ('motor_score', models.CharField(blank=True, default='', max_length=40)),
                ('total_score', models.IntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcs', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='EmsCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_in_charge', models.CharField(blank=True, default='', max_length=120)),
                ('ems_assistant_1', models.CharField(blank=True, default='', max_length=120)),
                ('ems_assistant_2', models.CharField(blank=True, default='', max_length=120)),
                ('ems_operator', models.CharField(blank=True, default='', max_length=120)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ems_crew', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Belongings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True, default='')),
                ('turned_over_to', models.CharField(blank=True, default='', max_length=120)),
                ('received_by', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='belongings', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='APGAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(blank=True, default='', max_length=80)),
                ('pulse', models.CharField(blank=True, default='', max_length=40)),
                ('grimace', models.CharField(blank=True, default='', max_length=80)),
                ('activity', models.CharField(blank=True, default='', max_length=80)),
                ('respiration', models.CharField(blank=True, default='', max_length=80)),
                ('total_score', models.IntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apgar', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, default='', max_length=30)),
                ('pulse_rate', models.CharField(blank=True, default='', max_length=30)),
                ('resp_rate', models.CharField(blank=True, default='', max_length=30)),
                ('resp_quality', models.CharField(blank=True, default='normal', max_length=40)),
                ('temperature_value', models.CharField(blank=True, default='', max_length=30)),
                ('temperature_state', models.CharField(blank=True, default='normal', max_length=30)),
                ('spo2', models.CharField(blank=True, default='', max_length=30)),
                ('skin_color', models.CharField(blank=True, default='normal', max_length=30)),
                ('pupils', models.CharField(blank=True, default='normal', max_length=30)),
                ('cap_refill', models.CharField(blank=True, default='normal', max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='reports.report')),
            ],
        ),
    ]
