# Generated by Django 6.0.2 on 2026-02-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='reports/attachments/'),
        ),
    ]
