# Generated by Django 6.0.2 on 2026-02-19 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_consciousness', models.CharField(blank=True, choices=[('awake', 'Awake'), ('verbal', 'Verbal'), ('pain', 'Pain'), ('unconscious', 'Unconscious')], default='awake', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='reports.report')),
            ],
        ),
    ]
