# Generated by Django 6.0.2 on 2026-02-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
