# Generated by Django 6.0.2 on 2026-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='case_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
