# Generated by Django 6.0.2 on 2026-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
