# Generated by Django 6.0.2 on 2026-04-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='level_of_consciousness',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('awake', 'Awake'), ('verbal', 'Verbal'), ('pain', 'Pain'), ('unconscious', 'Unconscious')], default='na', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chief_complaint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('na', 'N/A'), ('male', 'Male'), ('female', 'Female')], default='na', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='ambulance_body_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='report',
            name='call_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
