# Generated by Django 6.0.2 on 2026-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_incident_level_of_consciousness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='case_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('trauma', 'Trauma'), ('interfacility', 'Interfacility'), ('hostran', 'Hostran'), ('standby_medics', 'Standby Medics')], default='medical', max_length=30),
        ),
    ]
