# Generated by Django 6.0.2 on 2026-04-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_report_case_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='report',
            name='call_no',
        ),
        migrations.RemoveField(
            model_name='report',
            name='case_no',
        ),
    ]
