# Generated by Django 6.0.2 on 2026-04-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_patient_first_name_remove_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='case_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
