# Generated by Django 6.0.2 on 2026-04-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_report_case_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
