# Generated by Django 6.0.2 on 2026-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_patient_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='pulse_status',
            field=models.CharField(blank=True, default='na', max_length=40),
        ),
    ]
