# Generated by Django 6.0.2 on 2026-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_vital_pulse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='case_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('trauma', 'Trauma'), ('interfacility', 'Interfacility'), ('hostran', 'Hostran'), ('standby_medics', 'Standby Medics'), ('back_to_base', 'Back to Base')], default='medical', max_length=30),
        ),
    ]
