# Generated by Django 6.0.2 on 2026-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_report_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
