# Generated by Django 6.0.2 on 2026-04-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='left_hospital_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
