# Generated by Django 6.0.2 on 2026-04-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_report_left_hospital_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ambulance_body_no',
            field=models.CharField(blank=True, choices=[('', 'Select Ambulance'), ('PTV 70102', 'PTV 70102'), ('SND 2439', 'SND 2439'), ('SKA 1130', 'SKA 1130'), ('City Ambu 6651', 'City Ambu 6651')], default='', max_length=60),
        ),
    ]
