# Generated by Django 6.0.2 on 2026-05-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_alter_report_ambulance_body_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='connecting_runs',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('yes', 'Yes'), ('no', 'No')], default='na', max_length=10),
        ),
    ]
