"""
Django settings for ems_system project.
Generated by 'django-admin startproject' using Django 6.0.2
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-3h-e8d*joknldgp9&8!rvonjof2)=c)zhy%*dxl$m^lpf-em-x"

# Dev: set DJANGO_DEBUG=true
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.136.90",
]

# =========================
# Storage path fix
# =========================
def get_installed_backend_dir():
    """
    Development:
        Uses your project folder.

    Packaged backend:
        Uses the folder beside ems_backend.exe.

    Important:
        Do NOT use PyInstaller _MEI temp folder.
        Electron will pass EMS_DB_PATH and EMS_MEDIA_ROOT.
    """
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent

    return BASE_DIR


def get_sqlite_db_path():
    env_db_path = os.environ.get("EMS_DB_PATH")

    if env_db_path:
        db_path = Path(env_db_path).resolve()
    else:
        db_path = get_installed_backend_dir() / "db.sqlite3"

    db_path.parent.mkdir(parents=True, exist_ok=True)
    return db_path


def get_media_root():
    env_media_root = os.environ.get("EMS_MEDIA_ROOT")

    if env_media_root:
        media_path = Path(env_media_root).resolve()
    else:
        media_path = get_installed_backend_dir() / "media"

    media_path.mkdir(parents=True, exist_ok=True)
    return media_path


SQLITE_DB_PATH = get_sqlite_db_path()
MEDIA_ROOT = get_media_root()

print(f"[EMS] Using SQLite DB: {SQLITE_DB_PATH}")
print(f"[EMS] Using Media Root: {MEDIA_ROOT}")

# =========================
# Applications
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",

    "reports",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ems_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ems_system.wsgi.application"

# =========================
# Database
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(SQLITE_DB_PATH),
    }
}

# =========================
# Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# Internationalization
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True

# =========================
# Static files
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# =========================
# Media files
# =========================
MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# DRF + JWT Auth
# =========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# =========================
# CORS / CSRF
# =========================
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.136.90:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.136.90:3000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^null$",
    r"^file://.*$",
]